//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BrightnessSystemClientInternal.h"

@interface BrightnessSystemClient : NSObject
{
    BrightnessSystemClientInternal *bsci;
    OS_os_log *_logHandle;
}

- (void)unregisterNotificationForKeys:(id)arg1;
- (void)registerNotificationForKeys:(id)arg1;
- (void)unregisterNotificationForKey:(id)arg1;
- (void)registerNotificationForKey:(id)arg1;
- (void)registerNotificationBlock:(CDUnknownBlockType)arg1 forProperties:(id)arg2;
- (void)registerNotificationBlock:(CDUnknownBlockType)arg1;
- (BOOL)isAlsSupported;
- (id)copyPropertyForKey:(id)arg1;
- (BOOL)setProperty:(id)arg1 forKey:(id)arg2;
- (void)dealloc;
- (id)init;

@end

