//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BacklightSystemDelegateXpcProtocol-Protocol.h"
@class BrightnessSystemClientInternal;

__attribute__((visibility("hidden")))
@interface BrightnessSystemClientExportedObj : NSObject <BacklightSystemDelegateXpcProtocol>
{
    CDUnknownBlockType clientBlock;
    OS_dispatch_queue *queue;
    BrightnessSystemClientInternal *_target;
}

@property(nonatomic) BrightnessSystemClientInternal *target; // @synthesize target=_target;
- (void)notifyChangedProperty:(id)arg1 value:(id)arg2;
- (void)dealloc;
- (void)registerNotificationBlock:(CDUnknownBlockType)arg1;
- (void)unregisterNotificationBlock;

@end

