//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface NSDictionary (CBPropertyKeyExtension)
- (id)getKeyPropertyParameter;
- (id)getKeyCategoryRef;
- (unsigned long long)getKeyCategory;
- (id)getKeyDisplayIDRef;
- (unsigned long long)getKeyDisplayID;
- (id)getKeyString;
- (id)initWithPropertyKey:(id)arg1 andCategory:(unsigned long long)arg2;
- (id)initWithPropertyKey:(id)arg1;
- (id)initWithPropertyKey:(id)arg1 display:(unsigned long long)arg2 andParameter:(id)arg3;
- (id)initWithPropertyKey:(id)arg1 andDisplay:(unsigned long long)arg2;
@end

