//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface _CDContextualKeyPath : NSObject <NSCopying, NSSecureCoding>
{
    BOOL _isUserCentric;
    BOOL _isEphemeral;
    NSString *_key;
    unsigned long long _deviceID;
}

+ (BOOL)supportsSecureCoding;
+ (id)remotekeyPathForKeyPath:(id)arg1 forDevice:(unsigned long long)arg2;
+ (id)ephemeralKeyPathWithKey:(id)arg1;
+ (id)keyPathWithKey:(id)arg1;
+ (id)keyPathWithKey:(id)arg1 isUserCentric:(BOOL)arg2;
@property(nonatomic) BOOL isEphemeral; // @synthesize isEphemeral=_isEphemeral;
@property(nonatomic) BOOL isUserCentric; // @synthesize isUserCentric=_isUserCentric;
@property(nonatomic) unsigned long long deviceID; // @synthesize deviceID=_deviceID;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
// .cxx_destruct
- (unsigned short)characterAtIndex:(unsigned long long)arg1;
- (unsigned long long)length;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithKey:(id)arg1 forDevice:(unsigned long long)arg2 isUserCentric:(BOOL)arg3 isEphemeral:(BOOL)arg4;
- (id)init;

@end

