//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_CDUserContext-Protocol.h"
#import "_CDUserContextServerMonitoring-Protocol.h"

// //  NSCountedSet, NSMutableDictionary, OS_dispatch_queue, OS_os_log, NSString, NSXPCConnection, NSXPCListenerEndpoint;

@interface _CDClientContext : NSObject <_CDUserContext, _CDUserContextServerMonitoring>
{
    BOOL _interrupted;
    OS_dispatch_queue *_queue;
    OS_dispatch_queue *_xpcQueue;
    NSXPCConnection *_xpcConnection;
    NSXPCListenerEndpoint *_endpoint;
    NSMutableDictionary *_keyPathToValues;
    NSMutableDictionary *_registrations;
    NSCountedSet *_keyPathsWithRegistrationsForAnyChange;
    OS_dispatch_queue *_registrationCallbackQueue;
    NSMutableDictionary *_openRegistrationTokens;
    OS_os_log *_log;
}

+ (id)userContext;
+ (id)clientInterface;
+ (id)serverInterface;
@property(retain, nonatomic) OS_os_log *log; // @synthesize log=_log;
@property(retain, nonatomic) NSMutableDictionary *openRegistrationTokens; // @synthesize openRegistrationTokens=_openRegistrationTokens;
@property(retain, nonatomic) OS_dispatch_queue *registrationCallbackQueue; // @synthesize registrationCallbackQueue=_registrationCallbackQueue;
@property(retain, nonatomic) NSCountedSet *keyPathsWithRegistrationsForAnyChange; // @synthesize keyPathsWithRegistrationsForAnyChange=_keyPathsWithRegistrationsForAnyChange;
@property(retain, nonatomic) NSMutableDictionary *registrations; // @synthesize registrations=_registrations;
@property(retain, nonatomic) NSMutableDictionary *keyPathToValues; // @synthesize keyPathToValues=_keyPathToValues;
@property(nonatomic) BOOL interrupted; // @synthesize interrupted=_interrupted;
@property(retain, nonatomic) NSXPCListenerEndpoint *endpoint; // @synthesize endpoint=_endpoint;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property(retain, nonatomic) OS_dispatch_queue *xpcQueue; // @synthesize xpcQueue=_xpcQueue;
@property(retain, nonatomic) OS_dispatch_queue *queue; // @synthesize queue=_queue;
// .cxx_destruct
- (id)valuesForKeyPaths:(id)arg1 inContextsMatchingPredicate:(id)arg2;
- (id)localContext;
- (BOOL)addObjects:(id)arg1 andRemoveObjects:(id)arg2 fromArrayAtKeyPath:(id)arg3;
- (BOOL)removeObjects:(id)arg1 fromArrayAtKeyPath:(id)arg2;
- (BOOL)addObjects:(id)arg1 toArrayAtKeyPath:(id)arg2;
- (BOOL)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (BOOL)setObject:(id)arg1 forContextualKeyPath:(id)arg2;
- (void)handleRegistrationCompleted:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)handleContextualChange:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (BOOL)evaluatePredicate:(id)arg1;
- (void)deregisterCallback:(id)arg1;
- (void)cleanupInternalReferencesToRegistration:(id)arg1;
- (void)registerCallback:(id)arg1;
- (void)retryTimes:(int)arg1 block:(CDUnknownBlockType)arg2;
- (void)clearCacheForKeyPathsWithFireOnChangeRegistrations:(id)arg1;
- (void)removeKeyPathsWithRegistrationsForAnyChangeFromRegistration:(id)arg1;
- (void)addKeyPathsWithRegistrationsForAnyChangeFromRegistration:(id)arg1;
- (id)lastModifiedDateForContextualKeyPath:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForContextualKeyPath:(id)arg1;
- (void)setCachedValueIfClientHasRegistrations:(id)arg1 forKeyPath:(id)arg2;
- (id)cachedValueIfClientHasRegistrationsForKeyPath:(id)arg1;
- (BOOL)hasKnowledgeOfContextualKeyPath:(id)arg1;
- (void)dealloc;
- (id)initWithEndpoint:(id)arg1;
- (id)currentConnection;
- (void)unprotectedSetUpXPCConnectionWithEndpoint:(id)arg1;

@end

