//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBContainer.h"

#import "CBContainerProtocol-Protocol.h"
#import "CBHIDServiceProtocol-Protocol.h"
#import "CBStatusInfoProtocol-Protocol.h"
#import "NightShiftSupportProtocol-Protocol.h"

__attribute__((visibility("hidden")))
@interface CBColorModule : CBContainer <CBContainerProtocol, CBHIDServiceProtocol, NightShiftSupportProtocol, CBStatusInfoProtocol>
{
    NSMutableArray *_relevantServices;
    void *_callbackContext;
    _Bool _clamshell;
    OS_dispatch_source *_rampTimer;
    NSString *_userName;
    NSMutableDictionary *_properties;
    struct {
        struct ColorEffects *cfx;
        _Bool blueReductionEnabled;
        _Bool blueReductionFactor;
        _Bool nightModeSupported;
        _Bool fadeInProgress;
        _Bool enforceSlowRamps;
        float brightnessBoost;
        _Bool whitePointEnabled;
        double enablementTs;
        _Bool forceSnapping;
    } _colorStruct;
    _Bool _fadeInProgress;
    _Bool _endRamp;
    struct __IOHIDServiceClient *_dfr;
    struct {
        unsigned char firstTimerFire;
        OS_dispatch_source *logTimer;
        int periodS;
    } _reportContext;
    BOOL _displayOn;
    unsigned long long _moduleType;
}

@property(readonly) unsigned long long moduleType; // @synthesize moduleType=_moduleType;
- (id)copyIdentifiers;
- (id)newArrayFromIntegers:(int *)arg1 size:(int)arg2;
- (id)newArrayFromDoubles:(double *)arg1 size:(int)arg2;
- (BOOL)isDFR;
- (void)reportToAggd:(CDStruct_b1cf45a1 *)arg1;
- (void)commitPowerLogReport:(CDStruct_b1cf45a1 *)arg1;
- (void)reportCommitWithStop:(BOOL)arg1;
- (void)reportInitialize;
- (void)reportResetTimerWithStop:(BOOL)arg1;
- (BOOL)startNewTimerWithFreq:(float)arg1;
- (void)timerRoutine:(id)arg1;
- (void)initColorStruct;
- (void)colorRampRoutine:(const CDStruct_a0d89d44 *)arg1;
- (void)sendNotificationForKey:(id)arg1 andValue:(id)arg2;
- (void)updateActivity;
- (void)updateAvailability;
- (void)updateClamshellState:(_Bool)arg1;
- (_Bool)setProperty:(id)arg1 forKey:(id)arg2;
- (id)copyPropertyInternalForKey:(id)arg1;
- (id)copyPropertyForKey:(id)arg1;
- (void)switchToUser:(id)arg1;
- (void)setPreference:(id)arg1 forKey:(id)arg2 user:(id)arg3;
- (void)setPreferenceInternal:(id)arg1 forKey:(id)arg2 user:(id)arg3;
- (id)copyPreferenceForKey:(id)arg1 user:(id)arg2;
- (id)copyPreferenceInternalForKey:(id)arg1 user:(id)arg2;
- (void)setNightShiftFactorDictionary:(id)arg1;
- (_Bool)removeHIDServiceClient:(struct __IOHIDServiceClient *)arg1;
- (_Bool)addHIDServiceClient:(struct __IOHIDServiceClient *)arg1;
- (_Bool)handleHIDEvent:(struct __IOHIDEvent *)arg1 from:(struct __IOHIDServiceClient *)arg2;
- (void)handleHIDEventInternal:(struct __IOHIDEvent *)arg1 from:(struct __IOHIDServiceClient *)arg2;
- (_Bool)setPropertyInternal:(id)arg1 forKey:(id)arg2;
- (BOOL)BLRCCTTargetPropertyHandler:(id)arg1;
- (void)BLRFactorUpdate:(float)arg1 withPeriod:(float)arg2;
- (void)BLRFactorUpdate:(float)arg1;
- (BOOL)BLRFactorPropertyHandler:(id)arg1;
- (BOOL)clamshellStatePropertyHandler:(id)arg1;
- (void)displayBrightnessFactorUpdate:(float)arg1;
- (BOOL)displayBrightnessFactorPropertyHandler:(id)arg1;
- (void)dealloc;
- (void)stop;
- (BOOL)start;
- (id)initMain;

@end

