//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface CBPreferencesHandler : NSObject
{
}

+ (struct __CFDictionary *)copyPreferenceDictionaryForUser:(id)arg1;
+ (_Bool)storePreferenceForAllUsersMultiple:(id)arg1;
+ (id)copyPreferenceForAllUsersMultiple:(id)arg1;
+ (id)copyPreferenceForAllUsersForKey:(id)arg1;
+ (id)copyPreferenceForUser:(id)arg1 forKey:(id)arg2;
+ (_Bool)storePreferenceForAllUsersForKey:(id)arg1 andValue:(id)arg2;
+ (_Bool)storePreferenceForUser:(id)arg1 withKey:(id)arg2 andValue:(id)arg3;

@end

